events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx/app_cache
    levels=1:2
    keys_zone=app_cache:10m
    max_size=100m
    inactive=30m
    use_temp_path=off;

    upstream backend {
        server edge-backend:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host; 
        }
        location /health {
            return 200 "OK";
            add_header Content-Type text/plain;
        }
    }

}