events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx/app_cache
    levels=1:2
    keys_zone=app_cache:10m
    max_size=100m
    inactive=30m
    use_temp_path=off;

    upstream backend {
        server edge-backend:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host; 
        }
        location /health {
            return 200 "OK";
            add_header Content-Type text/plain;
        }
        location /api/v1/item/ {
            proxy_pass http://backend;
            proxy_cache app_cache;
            proxy_cache_key "$scheme$request_method$host$uri$is_args$args";
            proxy_cache_valid 200 304 1h; 
            proxy_cache_valid 404 1m;

            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https; 
        }
        location /api/v1/health/ {
            proxy_pass http://backend;
            proxy_cache app_cache;
            proxy_cache_key "$scheme$request_method$host$uri";
            proxy_cache_valid 200 304 1h; 
            proxy_cache_valid 404 1m;

            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https; 
        }

        location /api/no-cache {
            proxy_pass http://backend;
            proxy_cache_bypass 1;
            proxy_no_cache 1;
            add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https; 
        }
    }

}